### ISSUE TITLE
Erreur 500

### ISSUE THREAD

**Issue by greut** [HE-Arc/Flipero#1]
Indice 1

``` console
/var/www/.gem/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:304:in `block in replace_gem': puma is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    from /var/www/.gem/ruby/2.2.0/bin/puma:22:in `<main>'
```

Indice 2

``` console
~/www/app$ RAILS_ENV=production rails c
```

**Comment by LukasCH09** [comment]
@greut sauf erreur, cette erreur était avant que nous configurions le serveur. Il me semble que c'est résolu.

**Comment by greut** [comment]
@LukasBitter Si vous le dites. PS: `puma` est stoppé car sa configuration est mauvaise. Voir `/etc/service/puma/run` et `/var/www/config/puma.rb` puis redémarrez-le : `sudo sv start puma`.

**Comment by LucasBeltrame** [comment]
Quand on a fait le workshop avec Capistrano, il me semblait qu'il y avait quelque chose de spécial à faire avec nos clés publiques/privés pour SSH.

Car là, j'ai mis ma clé privé dans mon .ssh dans le container Docker (afin que Capistrano y ait accès pour se connecter).Sur le serveur, je n'ai rien ajouté vu qu'il y a déjà ma clé publique dans mon répertoire.

Est-ce qu'il faut ajouter la clé publique ailleurs également? (Je précise que j'arrive à me connecter en SSH depuis un terminal sans problème selon la méthode habituelle "ssh -p 2004 ...")

Quand je lance "cap staging deploy", j'ai un time out lors de la connexion en SSH.

> INFO [e70ce73d] Running /usr/bin/env mkdir -p /tmp/app/ as lucas@srvz-webapp.he-arc.ch
> DEBUG [e70ce73d] Command: /usr/bin/env mkdir -p /tmp/app/
> (Backtrace restricted to imported tasks)
> cap aborted!
> Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout

Je ne sais pas trop ce que je dois faire du coup :disappointed:

**Comment by LucasBeltrame** [comment]
@greut j'ai oublié de vous mentionner dans l'autre commentaire D:

**Comment by greut** [comment]
Ceci? https://github.com/HE-Arc/demo-rails-application/blob/master/config/deploy/staging.rb#L63

**Comment by LucasBeltrame** [comment]
Yep, effectivement ça fonctionne mieux maintenant. :relaxed: 

Merci !

**Comment by greut** [comment]
Cool.

**Comment by LucasBeltrame** [comment]
Même s'il manquait la ligne donc j'aurais eu des soucis par la suite, mon problème de SSH venait de mon utilisation de "Cisco AnyConnect" sur mon PC sous Debian (le VPN de l'école ne semble pas fournir d'adresse IP v6) et donc je n'arrivais plus à utiliser d'autres logiciels (comme Firefox par exemple).

En désactivant l'IP v6 sur ma machine, tout a refonctionné.
Voilà ça c'était juste pour dire d'où venait l'erreur que j'avais avant ! :)

Par contre, nous avons maintenant toujours l'erreur 500 qui s'affiche. J'ai bien regardé dans la config de nginx et puma et il me semble que tout est ok. En tout cas, les deux démarrent ! 

J'ai vérifié la config de nginx avec "sudo nginx -t" et tout est ok. (Si nginx ne fonctionnait pas, nous n'aurions pas la page d'erreur 500 de Rails de toute façon).

Puma ne semble pas générer d'erreurs particulière. La seule qu'il générait, c'était à cause de la clé secrète dont la variable d'environnement était absente du fichier .bash_profile. J'ai donc généré une clé via :

> rake secret

Et je l'ai donc ajouté dans mon fichier bash_profile.

J'ai regardé dans les logs ( /var/www/logs/error.log et, c'est la seule erreur qui apparaît :

> 2016/04/14 18:00:31 [error] 10116#10116: *33 connect() to unix:/tmp/puma.sock failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: flipero.srvz-webapp.he-arc.ch, request: "GET / HTTP/1.0", upstream: "http://unix:/tmp/puma.sock:/", host: "flipero.srvz-webapp.he-arc.ch"

J'ai cherché un peu sur le net et je n'ai pas trouvé de solution. Auriez-vous une idée?

Peut-être qu'au final, celle-ci vient de ce que vous mentionnez dans cette issue au final  :sweat_smile:

**Comment by greut** [comment]
```
flipero_1 | bundler: command not found: puma
flipero_1 | Install missing gem executables with `bundle install`
```

**edit:** c'était dans le README

https://github.com/HE-Arc/webapp-server/blob/master/files/templates/README-ror.md

**Comment by LucasBeltrame** [comment]
Merci de votre patience
![I'm done](http://i.giphy.com/3XiQswSmbjBiU.gif)

**Comment by greut** [comment]
np
![wastebasket + cat](http://i.imgur.com/3mKaPfm.gif)
