### ISSUE TITLE
manage end of sale

### ISSUE THREAD

**Issue by LukasCH09** [HE-Arc/Flipero#13]
using end_date field in slaes table and displaying a timer

**Comment by LucasBeltrame** [comment]
Les jobs sont mis en place
pour démarrer le process qui lancera les jobs, il faut entrer la commande suivante : 

bin/delayed_job start
(pour l'arrêter, c'est juste bin/delayed_job stop )

Pour le moment, le temps est réglé sur 1 minute pour la vente (pour des raisons de tests évidemment).

**Comment by greut** [comment]
Joli. Pourquoi `delayed_job` et pas un des backends proposé dans [la documentation](http://edgeguides.rubyonrails.org/active_job_basics.html#starting-the-backend) ?

**Comment by LucasBeltrame** [comment]
Je suis allé sur cette page : 
http://api.rubyonrails.org/classes/ActiveJob/QueueAdapters.html

Et il est dans la liste sur cette page et selon le petit tableau, il semblait avoir ce qui m'intéressait donc j'ai pris celui-ci. :)

**Comment by greut** [comment]
Okay, n'en changez pas mais prenez le temps de jeter un œil à cet article de 2009 : https://github.com/blog/542-introducing-resque (pour votre culture)

**Comment by LucasBeltrame** [comment]
Merci pour le lien :+1:

**Comment by LucasBeltrame** [comment]
commit e33c3a869eaff11323ffc06e388954cdc3657b81
