### ISSUE TITLE
Ajouter un logout

### ISSUE THREAD

**Issue by LucasBeltrame** [HE-Arc/Flipero#8]

**Comment by LukasCH09** [comment]
et gestion "fogot my password"?

**Comment by LucasBeltrame** [comment]
La gestion du logout est faite : 67d6975776578533ed8a514b95c813ba5e1866eb

Je vais regarder pour le "forgot my password"

**Comment by LukasCH09** [comment]
Du coup, il faudrait gérer les adresses emails pour envoyer un lien de ré-initialisation, je suppose

**Comment by LucasBeltrame** [comment]
Normalement, tout est géré par Devise. Il faudra juste que je configure l'envoi d'email et de voir si l'envoi d'email fonctionne (en regardant le mail catcher qu'on avait utilisé le semestre passé s'il n'est pas down :'D )

**Comment by LukasCH09** [comment]
Ok, sinon ici il y a quelques exemples: http://guides.rubyonrails.org/action_mailer_basics.html

**Comment by greut** [comment]
Ne dépensez pas trop d'énergie à gérer vos utilisateurs. Votre application a certainement des choses plus sexy à réaliser et, _in fine_ présenter.

**Comment by LukasCH09** [comment]
D'accord. Donc je propose que nous laissions de côté, pour l'instant, la gestion et l'envoi d'emails à l'utilisateur, et du coup aussi l'oubli de mot de passe.

**Comment by LucasBeltrame** [comment]
Yep j'approuve.
